### ISSUE TITLE
download not working

### ISSUE THREAD

**Issue by Tommy0412** [bipuldey19/Opensubtitles-Unofficial-API#2]
everything except download work. Can you fix it.

**Comment by bipuldey19** [comment]
Download is working just fine because I haven't stored any of their files. The download links are their own download links. And I have tried to download one and it's working. Thank you. 
![chrome_XO6gBM9Rgj](https://github.com/bipuldey19/Opensubtitles-Unofficial-API/assets/82335766/3046dc60-b369-40e0-b676-de7b8f0a4cf0)

**Comment by Tommy0412** [comment]
yes work for tv shows but not working for movies example https://opensubtitles.bymirrorx.eu.org/api/view?id=1043192
"download": "https://www.opensubtitles.orgundefined/",

**Comment by bipuldey19** [comment]
> yes work for tv shows but not working for movies example https://opensubtitles.bymirrorx.eu.org/api/view?id=1043192 "download": "https://www.opensubtitles.orgundefined/",

Your Problem is solved...

**Comment by Tommy0412** [comment]
still not working
